# Generated by Django 5.1.2 on 2024-10-27 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nose',
        ),
    ]
