# Generated by Django 5.1.2 on 2024-10-28 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
