# Generated by Django 5.1.2 on 2024-12-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_delete_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='TipoUsuario',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Colaborador', 'Colaborador')], max_length=20),
        ),
    ]
