# Generated by Django 5.1.2 on 2024-11-13 15:45

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProveedor', models.CharField(max_length=100, unique=True)),
                ('RutProveedor', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='RUT debe tener formato XX.XXX.XXX-X', regex='^[0-9]{1,2}\\.[0-9]{3}\\.[0-9]{3}-[0-9kK]$')])),
                ('MarcaProveedor', models.CharField(max_length=100, unique=True)),
                ('ComentarioProveedor', models.TextField(blank=True, null=True)),
                ('CiudadProveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('RegionProveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('PaisProveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('TelefonoProveedor', models.CharField(blank=True, max_length=15, null=True)),
                ('FotoProveedor', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen')),
                ('FechaCreacionProveedor', models.DateTimeField(auto_now_add=True)),
                ('FechaModificacionProveedor', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['NombreProveedor'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaEmision', models.DateField()),
                ('FotoFactura', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen')),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.proveedor')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-FechaEmision'],
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreEnvio', models.CharField(max_length=100)),
                ('CantidadEnvio', models.PositiveIntegerField()),
                ('PrecioEnvio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalEnvio', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('TipoEnvio', models.CharField(max_length=50)),
                ('FechaCompraEnvio', models.DateField(blank=True, null=True)),
                ('EnvioRecibido', models.BooleanField(default=False)),
                ('FechaRecibida', models.DateField(blank=True, null=True)),
                ('DescripcionEnvio', models.TextField(blank=True, null=True)),
                ('FotoEnvio', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen')),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.proveedor')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'ordering': ['-FechaCompraEnvio'],
            },
        ),
    ]
