# Generated by Django 5.1.2 on 2024-11-13 16:03

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='DocumentoFactura',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Documento de Factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='FechaEmision',
            field=models.DateField(verbose_name='Fecha de Emisión'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='FotoFactura',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto de Factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.proveedor', verbose_name='Proveedor'),
        ),
    ]
