# Generated by Django 5.1.2 on 2024-10-29 08:39

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProveedor', models.CharField(max_length=100, unique=True)),
                ('RutProveedor', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='RUT debe tener formato XX.XXX.XXX-X', regex='^[0-9]{1,2}\\.[0-9]{3}\\.[0-9]{3}-[0-9kK]$')])),
                ('MarcaProveedor', models.CharField(max_length=100, unique=True)),
                ('ComentarioProveedor', models.TextField(blank=True, null=True)),
                ('CiudadProveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('RegionProveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('PaisProveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('TelefonoProveedor', models.CharField(blank=True, max_length=15, null=True)),
                ('FotoProveedor', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['NombreProveedor'],
            },
        ),
    ]
