# Generated by Django 5.1.2 on 2024-11-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_factura_documentofactura_alter_factura_fechaemision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='documento_asset_id',
            field=models.CharField(blank=True, help_text='ID único del documento en Cloudinary', max_length=255, null=True, verbose_name='Asset ID del Documento'),
        ),
    ]
