# Generated by Django 5.1.2 on 2024-11-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_factura_documento_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='TipoEnvio',
            field=models.CharField(choices=[('material', 'Material'), ('herramienta', 'Herramienta')], help_text='Seleccione si el envío es de material o herramienta', max_length=50),
        ),
    ]
