# Generated by Django 5.1.2 on 2024-11-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_envio_tipoenvio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envio',
            old_name='FechaRecibida',
            new_name='FechaCompradaEnvio',
        ),
    ]
