# Generated by Django 5.1.2 on 2024-10-30 04:28

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreEnvio', models.CharField(max_length=100)),
                ('CantidadEnvio', models.PositiveIntegerField()),
                ('PrecioEnvio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalEnvio', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('TipoEnvio', models.CharField(max_length=50)),
                ('FechaCompraEnvio', models.DateField(blank=True, null=True)),
                ('EnvioRecibido', models.BooleanField(default=False)),
                ('FechaRecibida', models.DateField(blank=True, null=True)),
                ('DescripcionEnvio', models.TextField(blank=True, null=True)),
                ('FotoEnvio', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen')),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.proveedor')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'ordering': ['-FechaCompraEnvio'],
            },
        ),
    ]
