# Generated by Django 5.1.2 on 2024-11-09 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='EstadoProveedor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='FechaCreacionProveedor',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='FechaModificacionProveedor',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
