# Generated by Django 5.1.2 on 2024-11-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_fecharecibida_envio_fechacompradaenvio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='FechaCompradaEnvio',
        ),
        migrations.AddField(
            model_name='envio',
            name='DiasTranscurridos',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='envio',
            name='FechaCompraEnvio',
            field=models.DateField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
    ]
