# Generated by Django 5.1.2 on 2024-11-11 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_proveedor_estadoproveedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='EstadoProveedor',
        ),
    ]
