# Generated by Django 5.1.2 on 2024-11-15 05:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_envio_fechacompradaenvio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='HoraCreacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
