# Generated by Django 5.1.2 on 2024-11-15 05:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_envio_horacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='HoraCreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
