# Generated by Django 5.1.2 on 2024-11-16 03:05

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_envio_horacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreHerramienta', models.CharField(max_length=100)),
                ('StockHerramienta', models.PositiveIntegerField()),
                ('PrecioHerramienta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalHerramienta', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('FechaCompraHerramienta', models.DateField(auto_now_add=True)),
                ('MarcaHerramienta', models.CharField(max_length=100)),
                ('ModeloHerramienta', models.CharField(max_length=100)),
                ('UbicacionHerramienta', models.CharField(max_length=100)),
                ('FotoHerramienta', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen')),
                ('Envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.envio')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreMaterial', models.CharField(max_length=100)),
                ('StockMaterial', models.PositiveIntegerField()),
                ('PrecioMaterial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalMaterial', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('FechaCompraMaterial', models.DateField(auto_now_add=True)),
                ('DescripcionMaterial', models.TextField(blank=True, null=True)),
                ('ColorMaterial', models.CharField(blank=True, max_length=50, null=True)),
                ('PesoMaterial', models.CharField(blank=True, max_length=50, null=True)),
                ('DimensionesMaterial', models.CharField(blank=True, max_length=100, null=True)),
                ('DetalleMaterial', models.TextField(blank=True, null=True)),
                ('EstadoMaterial', models.CharField(max_length=50)),
                ('UbicacionMaterial', models.CharField(max_length=100)),
                ('FotoMaterial', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen')),
                ('Envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.envio')),
            ],
        ),
    ]
