# Generated by Django 5.1.2 on 2024-11-16 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_envio_id_herramienta_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='DescripcionHerramienta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='RegistroFacturaHerramienta',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2),
        ),
        migrations.AddField(
            model_name='material',
            name='RegistroFacturaMaterial',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='Envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.envio'),
        ),
        migrations.AlterField(
            model_name='material',
            name='Envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.envio'),
        ),
    ]
