# Generated by Django 5.1.2 on 2024-11-16 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_herramienta_descripcionherramienta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='Proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.proveedor'),
        ),
        migrations.AddField(
            model_name='material',
            name='Proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.proveedor'),
        ),
    ]
