# Generated by Django 5.1.2 on 2024-11-16 19:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_herramienta_proveedor_material_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='Factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='dashboard.factura', verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='factura',
            name='NumeroFactura',
            field=models.CharField(default=datetime.datetime(2024, 11, 16, 19, 1, 28, 997278, tzinfo=datetime.timezone.utc), help_text='Número o identificador único de la factura', max_length=50, verbose_name='Número de Factura'),
            preserve_default=False,
        ),
    ]
