# Generated by Django 5.1.2 on 2024-11-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_envio_factura_factura_numerofactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='MarcaHerramienta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='ModeloHerramienta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='UbicacionHerramienta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='EstadoMaterial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='UbicacionMaterial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
