# Generated by Django 5.1.2 on 2024-11-26 17:12

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_herramienta_marcaherramienta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCategoria', models.CharField(max_length=100, unique=True)),
                ('DescripcionCategoria', models.TextField(blank=True, null=True)),
                ('StockCategoria', models.PositiveIntegerField(default=0, editable=False)),
                ('FotoCategoria', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['NombreCategoria'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCliente', models.CharField(max_length=100)),
                ('ApellidoCliente', models.CharField(max_length=100)),
                ('RutCliente', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='RUT debe tener formato XX.XXX.XXX-X', regex='^[0-9]{1,2}\\.[0-9]{3}\\.[0-9]{3}-[0-9kK]$')])),
                ('TipoCliente', models.CharField(choices=[('particular', 'Particular'), ('empresa', 'Empresa')], default='particular', max_length=20)),
                ('NombreCompañia', models.CharField(blank=True, max_length=100, null=True)),
                ('ComentarioCliente', models.TextField(blank=True, null=True)),
                ('TelefonoCliente', models.CharField(blank=True, max_length=15, null=True)),
                ('FechaCliente', models.DateField(auto_now_add=True)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('UltimaModificacion', models.DateTimeField(auto_now=True)),
                ('Usuario', models.ForeignKey(blank=True, help_text='Usuario que registró al cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['NombreCliente'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProducto', models.CharField(max_length=100)),
                ('StockProducto', models.PositiveIntegerField()),
                ('PrecioUnitarioProducto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PrecioTotalProducto', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('CantidadProductoVendido', models.PositiveIntegerField(default=0, editable=False)),
                ('CantidadProductoDesechado', models.PositiveIntegerField(default=0, editable=False)),
                ('DescripcionProducto', models.TextField(blank=True, null=True)),
                ('UbicacionProducto', models.CharField(blank=True, max_length=100, null=True)),
                ('EstadoProducto', models.CharField(blank=True, max_length=50, null=True)),
                ('FechaProducto', models.DateField(auto_now_add=True)),
                ('DiasProducto', models.IntegerField(default=0, editable=False)),
                ('ProductoVendido', models.BooleanField(default=False)),
                ('HoraCreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('FotoProducto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='dashboard.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-FechaProducto'],
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreVenta', models.CharField(max_length=100)),
                ('CantidadVenta', models.PositiveIntegerField()),
                ('PrecioVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PrecioTotalVenta', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('FechaVenta', models.DateField(auto_now_add=True)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('Cliente', models.ForeignKey(blank=True, default=None, help_text='Cliente que realizó la compra', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='compras', to='dashboard.cliente')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='dashboard.producto')),
                ('Usuario', models.ForeignKey(help_text='Usuario que registró la venta', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-FechaVenta'],
            },
        ),
    ]
