# Generated by Django 5.1.2 on 2024-11-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_categoria_cliente_producto_ventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='StockProducto',
        ),
        migrations.AddField(
            model_name='producto',
            name='StockProductoActual',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Cantidad actual disponible (se actualiza automáticamente)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='StockProductoInicial',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad inicial del producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='ProductoVendido',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
