# Generated by Django 5.1.2 on 2024-11-27 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_producto_stockproducto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['NombreMaterial'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AddField(
            model_name='material',
            name='StockOriginal',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Stock inicial con el que se registró el material'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CantidadUsada', models.PositiveIntegerField(help_text='Cantidad del material utilizada en este producto')),
                ('DescripcionUso', models.TextField(blank=True, help_text='Descripción detallada de cómo se utilizó el material en el producto', null=True)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('UltimaModificacion', models.DateTimeField(auto_now=True)),
                ('Material', models.ForeignKey(help_text='Material utilizado en el producto', on_delete=django.db.models.deletion.PROTECT, related_name='productos_asociados', to='dashboard.material')),
                ('Producto', models.ForeignKey(help_text='Producto en el que se usó el material', on_delete=django.db.models.deletion.CASCADE, related_name='materiales_usados', to='dashboard.producto')),
            ],
            options={
                'verbose_name': 'Material del Producto',
                'verbose_name_plural': 'Materiales del Producto',
                'ordering': ['Producto', 'Material'],
                'unique_together': {('Producto', 'Material')},
            },
        ),
    ]
