# Generated by Django 5.1.2 on 2024-11-27 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_material_options_material_stockoriginal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='dashboard.categoria'),
        ),
    ]
