# Generated by Django 5.1.2 on 2024-11-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_producto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='ProductoVendido',
            new_name='ProductoAgotado',
        ),
        migrations.AddField(
            model_name='producto',
            name='Materiales',
            field=models.ManyToManyField(related_name='productos', through='dashboard.ProductoMaterial', to='dashboard.material'),
        ),
    ]
