# Generated by Django 5.1.2 on 2024-11-30 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_rename_productovendido_producto_productoagotado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomaterial',
            name='Material',
            field=models.ForeignKey(help_text='Material utilizado en el producto', on_delete=django.db.models.deletion.CASCADE, related_name='productos_asociados', to='dashboard.material'),
        ),
    ]
