# Generated by Django 5.1.2 on 2024-12-01 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_productomaterial_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='Cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Venta',
            field=models.ForeignKey(blank=True, help_text='Venta asociada al cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.ventas'),
        ),
    ]
