# Generated by Django 5.1.2 on 2024-12-01 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_ventas_cliente_cliente_venta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perdidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePerdida', models.CharField(max_length=100)),
                ('CantidadPerdida', models.PositiveIntegerField()),
                ('ValorUnitarioPerdida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ValorTotalPerdida', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('FechaPerdida', models.DateField(auto_now_add=True)),
                ('MotivoPerdida', models.CharField(choices=[('caducidad', 'Caducidad'), ('daño', 'Daño'), ('robo', 'Robo'), ('error_inventario', 'Error de Inventario'), ('otros', 'Otros')], default='otros', max_length=20)),
                ('DescripcionPerdida', models.TextField(blank=True, null=True)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('UltimaModificacion', models.DateTimeField(auto_now=True)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perdidas', to='dashboard.producto')),
                ('Usuario', models.ForeignKey(help_text='Usuario que registró la pérdida', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pérdida',
                'verbose_name_plural': 'Pérdidas',
                'ordering': ['-FechaPerdida'],
            },
        ),
    ]
