# Generated by Django 5.1.2 on 2024-12-01 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_perdidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdidas',
            name='Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perdidas', to='dashboard.producto'),
        ),
    ]
