# Generated by Django 5.1.2 on 2024-12-01 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_perdidas_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='dashboard.producto'),
        ),
    ]
