# Generated by Django 5.1.2 on 2024-12-02 01:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_ventas_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ApellidoCliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ComentarioCliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='FechaCliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='FechaRegistro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='NombreCliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='NombreCompañia',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='RutCliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='TelefonoCliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='TipoCliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='UltimaModificacion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Venta',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, help_text='Dirección del cliente', null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo electrónico del cliente', max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default=1, help_text='Nombre del cliente', max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono del cliente', max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='dashboard.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='CantidadVenta',
            field=models.PositiveIntegerField(verbose_name='Cantidad vendida'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='FechaVenta',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de venta'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='NombreVenta',
            field=models.CharField(max_length=100, verbose_name='Nombre de la venta'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='PrecioTotalVenta',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='PrecioVenta',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='dashboard.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='Usuario',
            field=models.ForeignKey(help_text='Usuario que registró la venta', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
