# Generated by Django 5.1.2 on 2024-12-02 01:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_cliente_options_remove_cliente_apellidocliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['NombreCliente'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ultima_modificacion',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='ApellidoCliente',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='ComentarioCliente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='FechaCliente',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='NombreCliente',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='NombreCompañia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='RutCliente',
            field=models.CharField(default=1, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='RUT debe tener formato XX.XXX.XXX-X', regex='^[0-9]{1,2}\\.[0-9]{3}\\.[0-9]{3}-[0-9kK]$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='TelefonoCliente',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='TipoCliente',
            field=models.CharField(choices=[('particular', 'Particular'), ('empresa', 'Empresa')], default='particular', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='UltimaModificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró al cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Venta',
            field=models.ForeignKey(blank=True, help_text='Venta asociada al cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.ventas'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='CantidadVenta',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='FechaVenta',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='NombreVenta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='PrecioTotalVenta',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='PrecioVenta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='dashboard.producto'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='Usuario',
            field=models.ForeignKey(help_text='Usuario que registró la venta', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
