# Generated by Django 5.1.2 on 2024-12-02 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_cliente_options_remove_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Venta',
        ),
        migrations.AddField(
            model_name='ventas',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente asociado a la venta (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='dashboard.cliente'),
        ),
    ]
