# Generated by Django 5.1.2 on 2024-12-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_remove_cliente_venta_ventas_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='CantidadCategoriaPerdida',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Cantidad total de productos perdidos en esta categoría'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='CantidadCategoriaVenta',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Cantidad total de productos vendidos en esta categoría'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='DineroCategoriaPerdida',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Valor total en dinero de las pérdidas en esta categoría', max_digits=12),
        ),
        migrations.AddField(
            model_name='categoria',
            name='DineroCategoriaVenta',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Valor total en dinero de las ventas en esta categoría', max_digits=12),
        ),
        migrations.AddField(
            model_name='categoria',
            name='TotalCategoriaPerdida',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Total acumulado de pérdidas en esta categoría', max_digits=12),
        ),
        migrations.AddField(
            model_name='categoria',
            name='TotalCategoriaVenta',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Total acumulado de ventas en esta categoría', max_digits=12),
        ),
        migrations.AddField(
            model_name='cliente',
            name='CantidadTotalCompras',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Cantidad total de productos comprados por el cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='TotalDineroCompras',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Total en dinero de todas las compras del cliente', max_digits=12),
        ),
    ]
