# Generated by Django 5.1.2 on 2024-12-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_categoria_cantidadcategoriaperdida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='DineroCategoriaPerdida',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='DineroCategoriaVenta',
        ),
    ]
