# Generated by Django 5.1.2 on 2024-12-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_remove_categoria_dinerocategoriaperdida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='cliente_eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
