# Generated by Django 5.1.2 on 2024-12-12 06:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_ventas_cliente_eliminado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ApellidoCliente',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El apellido solo debe contener letras y espacios', regex='^[A-Za-zÁáÉéÍíÓóÚúÜüÑñ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='NombreCliente',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo debe contener letras y espacios', regex='^[A-Za-zÁáÉéÍíÓóÚúÜüÑñ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='RutCliente',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='TelefonoCliente',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener formato +569XXXXXXXX o 569XXXXXXXX', regex='^\\+?569\\d{8}$')]),
        ),
        migrations.CreateModel(
            name='Producto_Respaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaEliminacion', models.DateTimeField(auto_now_add=True)),
                ('NombreProducto', models.CharField(max_length=100)),
                ('StockProductoInicial', models.PositiveIntegerField()),
                ('StockProductoActual', models.PositiveIntegerField()),
                ('PrecioUnitarioProducto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PrecioTotalProducto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CategoriaOriginal', models.CharField(blank=True, max_length=100, null=True)),
                ('MaterialesUsados', models.TextField(blank=True, null=True)),
                ('CantidadProductoVendido', models.PositiveIntegerField()),
                ('CantidadProductoDesechado', models.PositiveIntegerField()),
                ('DescripcionProducto', models.TextField(blank=True, null=True)),
                ('UbicacionProducto', models.CharField(blank=True, max_length=100, null=True)),
                ('EstadoProducto', models.CharField(blank=True, max_length=50, null=True)),
                ('FechaProducto', models.DateField()),
                ('DiasProducto', models.IntegerField()),
                ('ProductoAgotado', models.BooleanField()),
                ('FotoProductoURL', models.URLField(blank=True, null=True)),
                ('EliminadoPor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto en Respaldo',
                'verbose_name_plural': 'Productos en Respaldo',
                'ordering': ['-FechaEliminacion'],
            },
        ),
    ]
